### ISSUE TITLE
Debian nomenclature and concepts

### ISSUE THREAD

**Issue by guillemj** [Slookeur/OPEN#6]
Hi!

On the `Software build` section, it is stated that the programming language used is of no importance, although that does influence how one does packaging in Debian, due to the packaging helpers and tools used, and additional fields and conventions used, in addition of how to hook into their respective build systems.

While skimming over the Debian sections, I noticed some odd nomenclature usage.

What is being referred as sections (such as `Build-Depends`) or keywords, is known instead as a field.
What is being referred as `Package:` instructions is known as stanzas (the paragraph blocks describing each binary package).
The `Standards-Version` field refers to the last Debian Policy the package was checked against, it serves as a bookmark, to know where to start once you need to update the packaging against new standards (see the Debian Policy upgrade checklist).
The `Section` field is used mainly by package manager front-ends or package web portals, it does not really influence where the application will show up in GUI or Desktop menus or similar, that would usually be specified as part of the `.desktop` files.

**Comment by Slookeur** [comment]
Thank you, 
I will check this, and will get back to you in this thread when done. 

Again thank you for taking the time to dig into this work. 

Regards

**Comment by Slookeur** [comment]
Hello, 
I finally took the time to consider properly your remarks and amended the document accordingly, sorry that it took me so long to do the job.

Thanks again.
