### ISSUE TITLE
Deprecated references to pkg-config

### ISSUE THREAD

**Issue by guillemj** [Slookeur/OPEN#7]
Hi!

At least in Debian the `pkg-config` implementation is being phased out in favor of the `pkgconf` upstream project, which is maintained, interface compatible and fixes several of long-standing issues with `pkg-config`.

So it might be nice to replace references to `pkg-config` with `pkgconf.` Although the tool can still be accessed as `pkg-config`.

There's also an example to find the `pkg-config` tool using `AC_CHECK_PROG`, but that will not work for cross-compilation, so it would be better to recommend instead `PKG_PROG_PKG_CONFIG`

**Comment by Slookeur** [comment]
I am learning this reading you, I will take time to correct this, and close this when done. 

Thank you for taking the time to comment on this.

**Comment by Slookeur** [comment]
Hello, 
I finally had the time to correct the manual following your remarks, thanks again and sorry that it took so long.

Regards.
